managers:
  - name: version
    configuration:
      maintainers:
        - harshad16
        - goern
        - fridex
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: false
